// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwuiUS2JS0yiQI8P4tngFZc41NSXh09g',
    appId: '1:634424633336:android:ff1d864e718ce89284d80d',
    messagingSenderId: '634424633336',
    projectId: 'jurnee-f0ef7',
    storageBucket: 'jurnee-f0ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFSKSX3GRyQ2huUYB7Cxft0Q3IXH-rD8',
    appId: '1:634424633336:ios:1f051525828a3d0684d80d',
    messagingSenderId: '634424633336',
    projectId: 'jurnee-f0ef7',
    storageBucket: 'jurnee-f0ef7.firebasestorage.app',
    androidClientId: '634424633336-lqf5bt0k5pq6u7h60tp93k6o9l74o3f2.apps.googleusercontent.com',
    iosClientId: '634424633336-iafq9emvgsdqss0k6js8aggd4bn2jt5e.apps.googleusercontent.com',
    iosBundleId: 'com.joinjurnee.jurnee',
  );

}